ec2:
  hosts:
    vpn:
      ansible_host: ec2-54-204-107-45.compute-1.amazonaws.com
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/vpn.pem
home:
  hosts:
    steven:
      ansible_host: steven
      ansible_user: sam
      vpn_ip: 10.5.0.2
    mitch:
      ansible_host: mitch
      ansible_user: sam
      vpn_ip: 10.5.0.3
    laptop:
      ansible_host: laptop
      ansible_user: sam
      vpn_ip: 10.5.0.4
    ec2-54-152-94-194.compute-1.amazonaws.com:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/vpn.pem
      vpn_ip: 10.5.0.5
nfs:
  hosts:
    nfs:
      ansible_host: steven
      ansible_user: sam
      nfs_dir: /mnt/nfs
    
