---
- name: install nfs server
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-kernel-server

- name: add nfs exports
  lineinfile:
    path: /etc/exports
    line: "{{ item }}"
    create: yes
  with_items:
  - "{{ hostvars['nfs']['nfs_dir'] }} 192.168.86.1/24(rw,sync,no_subtree_check,no_root_squash)"

- name: export nfs
  command: exportfs -a

- name: restart nfs server
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: yes